{% set name = "regex" %}
{% set version = "2024.9.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6c188c307e8433bcb63dc1915022deb553b4203a70722fc542c363bf120a01fd

build:
  number: 0
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - wheel
    - setuptools
  run:
    - python

test:
  imports:
    - regex
    - regex.regex
    - regex._regex_core
    - regex.test_regex
  requires:
    - pip
  commands:
    - pip check
    - python -m unittest -v regex.test_regex

about:
  home: https://github.com/mrabarnett/mrab-regex
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: Alternative regular expression module, to replace re
  description: |
    This regex implementation is backwards-compatible with the standard 're' module, but offers additional functionality.
  doc_url: https://github.com/mrabarnett/mrab-regex/blob/hg/README.rst
  dev_url: https://github.com/mrabarnett/mrab-regex

extra:
  recipe-maintainers:
    - kwilcox
    - ocefpaf
    - xhochy
