{% set version = "2021.11.1" %}

package:
  name: regex
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/r/regex/regex-{{ version }}.tar.gz
  sha256: 20675d8bd3c2cc8dbfafd60a220ec04d0018564f101f80a64e56f4e4ed0afe55

build:
  number: 0
  skip: true  # [win and py27]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - wheel
    - setuptools
  run:
    - python

test:
  imports:
    - regex
  requires:
    - pip
  commands:
    - pip check


about:
  home: https://bitbucket.org/mrabarnett/mrab-regex
  license: Apache 2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: Alternative regular expression module, to replace re
  doc_url: https://bitbucket.org/mrabarnett/mrab-regex/src/hg/docs/Features.rst
  dev_url: https://bitbucket.org/mrabarnett/mrab-regex/src/hg/

extra:
  recipe-maintainers:
    - kwilcox
    - ocefpaf
    - xhochy
