{% set version = "2017.02.08" %}

package:
  name: regex
  version: {{ version }}

source:
  fn: regex-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/r/regex/regex-{{ version }}.tar.gz
  sha256: 45b62acff46cb886246e40227a872089d8d4972dbf2f114ec1ae64e5893e87bf

build:
  number: 0
  script: python setup.py install

requirements:
  build:
    - python
  run:
    - python

test:
  imports:
    - regex

about:
  home: https://bitbucket.org/mrabarnett/mrab-regex
  license: Python-2.0
  summary: 'Alternative regular expression module, to replace re.'

extra:
  recipe-maintainers:
    - kwilcox
    - ocefpaf
