{% set version = "2018.11.22" %}

package:
  name: regex
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/r/regex/regex-{{ version }}.tar.gz
  sha256: 79a6a60ed1ee3b12eb0e828c01d75e3b743af6616d69add6c2fde1d425a4ba3f

build:
  number: 1000
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - regex

about:
  home: https://bitbucket.org/mrabarnett/mrab-regex
  license: Python-2.0
  license_family: PSF
  summary: 'Alternative regular expression module, to replace re.'

extra:
  recipe-maintainers:
    - kwilcox
    - ocefpaf
    - xhochy
