{% set version = "2019.04.12" %}

package:
  name: regex
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/r/regex/regex-{{ version }}.tar.gz
  sha256: 7ca6e9b1d8757af3d8e23bd21391a3362a53c644d60931853da7f8d072e6b3ff

build:
  number: 0
  skip: True  # [win and py27]
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - regex

about:
  home: https://bitbucket.org/mrabarnett/mrab-regex
  license: Python-2.0
  license_family: PSF
  summary: 'Alternative regular expression module, to replace re.'

extra:
  recipe-maintainers:
    - kwilcox
    - ocefpaf
    - xhochy
