{% set version = "2018.06.09" %}

package:
  name: regex
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/r/regex/regex-{{ version }}.tar.gz
  sha256: 0201b4cb42f03842a75044a3d08b62a79114f753b33ee421182c631d9f5c81f5

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
  build:
    - {{ compiler('c') }}
  run:
    - python

test:
  imports:
    - regex

about:
  home: https://bitbucket.org/mrabarnett/mrab-regex
  license: Python-2.0
  license_family: PSF
  summary: 'Alternative regular expression module, to replace re.'

extra:
  recipe-maintainers:
    - kwilcox
    - ocefpaf
