{% set version = "2016.11.18" %}

package:
  name: regex
  version: {{ version }}

source:
  fn: regex-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/r/regex/regex-{{ version }}.tar.gz
  sha256: 869918f4d5444e4526a2df7e0f34f324d87e998650e775e8bbc3963296d0cd88

build:
  number: 0
  script: python setup.py install

requirements:
  build:
    - python
  run:
    - python

test:
  imports:
    - regex

about:
  home: https://bitbucket.org/mrabarnett/mrab-regex
  license: Python-2.0
  summary: 'Alternative regular expression module, to replace re.'

extra:
  recipe-maintainers:
    - kwilcox
    - ocefpaf
