{% set name = "regex" %}
{% set version = "2022.7.9" %}
{% set build_number = "0" %}
{% set checksum = "601c99ac775b6c89699a48976f3dbb000b47d3ca59362c8abc9582e6d0780d91" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/r/regex/regex-{{ version }}.tar.gz
  sha256: {{ checksum }}

build:
  number: {{ build_number }}
  # the minimal version of python supported is python 3.6
  skip: true  # [py<36]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - wheel
    - setuptools
  run:
    - python

test:
  imports:
    - regex
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/mrabarnett/mrab-regex
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: Alternative regular expression module, to replace re
  doc_url: https://github.com/mrabarnett/mrab-regex/blob/hg/README.rst
  dev_url: https://github.com/mrabarnett/mrab-regex

extra:
  recipe-maintainers:
    - kwilcox
    - ocefpaf
    - xhochy
