{% set name = "regex" %}
{% set version = "2023.8.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fcbdc5f2b0f1cd0f6a56cdb46fe41d2cce1e644e3b68832f3eeebc5fb0f7712e

build:
  number: 0
  # the minimal version of python supported is python 3.7
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - wheel
    - setuptools
  run:
    - python

test:
  imports:
    - regex
  requires:
    - pip
  commands:
    - pip check
    - python -m unittest -v regex.test_regex

about:
  home: https://github.com/mrabarnett/mrab-regex
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: Alternative regular expression module, to replace re
  description: |
    This regex implementation is backwards-compatible with the standard 're' module, 
    but offers additional functionality.
  doc_url: https://github.com/mrabarnett/mrab-regex/blob/hg/README.rst
  dev_url: https://github.com/mrabarnett/mrab-regex

extra:
  recipe-maintainers:
    - kwilcox
    - ocefpaf
    - xhochy
