{% set version = "2016.08.27" %}

package:
    name: regex
    version: {{ version }}

source:
    fn: regex-{{ version }}.tar.gz
    url: https://pypi.io/packages/source/r/regex/regex-{{ version }}.tar.gz
    sha256: 53b97d85ebcbae7536dc24e798da114551a50de925a565ca14df17e6aa562389

build:
    number: 0
    script: python setup.py install

requirements:
    build:
        - python
    run:
        - python

test:
    imports:
        - regex

about:
    home: https://bitbucket.org/mrabarnett/mrab-regex
    license: Python-2.0
    summary: Alternative regular expression module, to replace re.

extra:
    recipe-maintainers:
        - kwilcox
        - ocefpaf
