{% set version = "2021.11.2" %}

package:
  name: regex
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/r/regex/regex-{{ version }}.tar.gz
  sha256: 5e85dcfc5d0f374955015ae12c08365b565c6f1eaf36dd182476a4d8e5a1cdb7

build:
  number: 0
  skip: true  # [win and py27]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - wheel
    - setuptools
  run:
    - python

test:
  imports:
    - regex
  requires:
    - pip
  commands:
    - pip check


about:
  home: https://bitbucket.org/mrabarnett/mrab-regex
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: Alternative regular expression module, to replace re
  doc_url: https://bitbucket.org/mrabarnett/mrab-regex/src/hg/docs/Features.rst
  dev_url: https://bitbucket.org/mrabarnett/mrab-regex/src/hg/

extra:
  recipe-maintainers:
    - kwilcox
    - ocefpaf
    - xhochy
