{% set version = "2022.3.15" %}

package:
  name: regex
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/r/regex/regex-{{ version }}.tar.gz
  sha256: 0a7b75cc7bb4cc0334380053e4671c560e31272c9d2d5a6c4b8e9ae2c9bd0f82

build:
  number: 0
  # trigger 1
  # the minimal version of python supported is python 3.6
  skip: true  # [py<36]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - wheel
    - setuptools
  run:
    - python

test:
  imports:
    - regex
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/mrabarnett/mrab-regex
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: Alternative regular expression module, to replace re
  doc_url: https://github.com/mrabarnett/mrab-regex/blob/hg/README.rst
  dev_url: https://github.com/mrabarnett/mrab-regex

extra:
  recipe-maintainers:
    - kwilcox
    - ocefpaf
    - xhochy
