{% set version = "2016.06.19" %}

package:
    name: regex
    version: {{ version }}

source:
    fn: regex-{{ version }}.tar.gz
    url: https://pypi.io/packages/source/r/regex/regex-{{ version }}.tar.gz
    md5: d10f923cdda1a6cb674bbecc9440f42b

build:
    number: 0
    script: python setup.py install

requirements:
    build:
        - python
    run:
        - python

test:
    imports:
        - regex

about:
    home: https://bitbucket.org/mrabarnett/mrab-regex
    license: Python-2.0
    summary: Alternative regular expression module, to replace re.

extra:
    recipe-maintainers:
        - kwilcox
        - ocefpaf
