{% set version = "2022.3.2" %}

package:
  name: regex
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/r/regex/regex-{{ version }}.tar.gz
  sha256: 79e5af1ff258bc0fe0bdd6f69bc4ae33935a898e3cbefbbccf22e88a27fa053b

build:
  number: 0
  # the minimal version of python supported is python 3.6
  skip: true  # [py<36]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - wheel
    - setuptools
  run:
    - python

test:
  imports:
    - regex
  requires:
    - pip
  commands:
    - pip check


about:
  home: https://bitbucket.org/mrabarnett/mrab-regex
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: Alternative regular expression module, to replace re
  doc_url: https://bitbucket.org/mrabarnett/mrab-regex/src/hg/docs/Features.rst
  dev_url: https://bitbucket.org/mrabarnett/mrab-regex/src/hg/

extra:
  recipe-maintainers:
    - kwilcox
    - ocefpaf
    - xhochy
