{% set version = "2017.09.23" %}

package:
  name: regex
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/r/regex/regex-{{ version }}.tar.gz
  sha256: 80166c9e21c0171c7b502035f3ba25f43b5122def387ca6ba9706b6892fed7aa

build:
  number: 0
  script: python -m pip install --no-deps .

requirements:
  host:
    - python
    - pip
  build:
    - {{ compiler('c') }}
  run:
    - python

test:
  imports:
    - regex

about:
  home: https://bitbucket.org/mrabarnett/mrab-regex
  license: Python-2.0
  summary: 'Alternative regular expression module, to replace re.'

extra:
  recipe-maintainers:
    - kwilcox
    - ocefpaf
