# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_python2.7
    - CONFIG=osx_python3.5
    - CONFIG=osx_python3.6

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "LWTntcHYcTL52KeQlWlSBqMBIjPmgZ+dxk7ficDMVRceR0WVmYSc2NZS1sX+LRph+AYbmJeEcPl2qomoStT/0YfnqVQJLLK94ICdv2zMa/fbmHr7yVIWAfI6IbXh5sX3gjKKwF6ztDYhH/wQo8jRFdRPmRlSfeHYHDHYZBEHZ+N7sNxOQ0/dMCrjsXPa9xBdRMRFTnz/9Vp22uz7zPnd4fXcYt1XZrY9uBGqy9v47xpcQrP4sQ0YIy+ecYp21kcme7cYZ3wZMaL5fsqVcT/sycj19Gxoc3dQt+iQlNjYd24GtUzh5lBWI8O8OQJpE7cj4yesMFbnJJiJ8ddzQltyCxkLaAOkrQsee3U30mNe7zb3ANc2tEfZQ3AumGwbPwUIyC/rWj3xMHVxjwW1mWVTV/YrUUfDP+zBQdrjVnn7uFKCRweclknSY4zpe7O4Tmh/5smXLOC2Yl8hh9yaVFS4xL4fmsLh9nu52Dyebxo0sa7zEa/q126vbJNhWmTAP50X65VaqQt8ipvRwERSKdA1XbVH0yTrhcsECy91UtWLLobBY8YPJWxG6vwxCZf1V1gVd/LRmyroGWhsX3D6dWO6R6d0uRzUgPYUfbzdz0ar4INfeOKPXHVzfpdAXRWXxqkL1rW2gHxs0kUMZFWsr0HtRcnBSMO4XrUFSIEd8LtTB5U="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-ci-setup=1
      source run_conda_forge_build_setup

script:
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml

  - upload_or_check_non_existence ./recipe conda-forge --channel=main -m ./.ci_support/${CONFIG}.yaml
