travis:
  secure:
    BINSTAR_TOKEN: Lk84YI6ZvDkkJkZuvpTfiBdUn8BuuJCNQTOd1bmf+rStcDKuS3/GADxbWSLhemdA/viGq7TPqQJs3U64lP2RilmZBVUnrGd+rn7nGCzvU4rM3jd5tjBwaztPDON1dc0x4mo0fCYGFCn67OaVnPXX8tPb3o9dsiRKxekem4pEPztZnmdXgbHaExHHt5u1Fi2ArLaTnE1YYa0bdth1b63Z1fX4RVLX1RIEIgSCiVjw7j204xJTja1ZDUq56+LD2nF35bdIasHXMjZgMYzqCKIqZtkzJA3xjTxEtHzFrcr5g5OKsUkfT80Fk0a+MsFI9ENtbfiXMxadlzJx6mv1WM8YnuF1yhwAOcdpuK2bDPf+jRm3gUcPRRlrAedNlmJ+o89Y9x92aqn9mrvdz0Uu5tQaQPq/JnVWPz8SUNUBK9f3AnjGrtPuM4vW2BaLBgHw+6+O38U6c+vPChfKPsWBRCCeMV55ECj5hynH/CtodlX1c8sFGzjXZ/Yi3HcCHYPvZWJQDUN3FBsDeOMugdeHkhqfkAWmGB3so89R+Y2w8GmGLy2Yabv1SsppPZGvl77ChICz/zHatzxFA/783WDMbXjndOiU0Nk40QX0B5uTiIFRJplo3i4Cr8ngYWLBgYUZwqdIkCN1UHluVq0HdsxLif7nj65AyfWodf7+ywLxedKECWc=
appveyor:
  secure:
    BINSTAR_TOKEN: /XxwAsgp0EItmAhoPSov/h0BtAFNj2BuuEqnhgaP9l7Rw2yLBM1lD+3q4LvpVm3B
