travis:
  secure:
    BINSTAR_TOKEN: LWTntcHYcTL52KeQlWlSBqMBIjPmgZ+dxk7ficDMVRceR0WVmYSc2NZS1sX+LRph+AYbmJeEcPl2qomoStT/0YfnqVQJLLK94ICdv2zMa/fbmHr7yVIWAfI6IbXh5sX3gjKKwF6ztDYhH/wQo8jRFdRPmRlSfeHYHDHYZBEHZ+N7sNxOQ0/dMCrjsXPa9xBdRMRFTnz/9Vp22uz7zPnd4fXcYt1XZrY9uBGqy9v47xpcQrP4sQ0YIy+ecYp21kcme7cYZ3wZMaL5fsqVcT/sycj19Gxoc3dQt+iQlNjYd24GtUzh5lBWI8O8OQJpE7cj4yesMFbnJJiJ8ddzQltyCxkLaAOkrQsee3U30mNe7zb3ANc2tEfZQ3AumGwbPwUIyC/rWj3xMHVxjwW1mWVTV/YrUUfDP+zBQdrjVnn7uFKCRweclknSY4zpe7O4Tmh/5smXLOC2Yl8hh9yaVFS4xL4fmsLh9nu52Dyebxo0sa7zEa/q126vbJNhWmTAP50X65VaqQt8ipvRwERSKdA1XbVH0yTrhcsECy91UtWLLobBY8YPJWxG6vwxCZf1V1gVd/LRmyroGWhsX3D6dWO6R6d0uRzUgPYUfbzdz0ar4INfeOKPXHVzfpdAXRWXxqkL1rW2gHxs0kUMZFWsr0HtRcnBSMO4XrUFSIEd8LtTB5U=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
